
# Banned Words List
# Source:
# Reddit post: https://www.reddit.com/r/youtubers/comments/db5kgt/tips_tricks_list_of_youtube_demonetized_words_for/
# spread sheet: https://docs.google.com/spreadsheets/u/1/d/1ozg1Cnm6SdtM4M5rATkANAi07xAzYWaKL7HKxyvoHzk/htmlview#

banned_words = ["blacklisted", "blackmail", "blackmailed", "blackmailing", "blacks", "bladder cancer", "blade",
"blades", "blogs", "blonde", "blonde action", "blood poisoning", "bloody", "blow", "blow job", "blowing", "blowjob", "blowjobs",
"blue anon", "blue balls", "blunt", "bluray", "blyat", "bod", "bodies", "body art", "body paint", "body painting",
"bodysuit", "boil", "boipucci", "boipussy", "boko haram", "boku no pico", "bold", "bomb", "bombed", "bomber", "bombers",
"bombing", "bond", "bondage", "bone", "boned", "boner", "boners", "bong", "boob", "boobies", "boobs", "booby", "booking",
"bookings", "booobs", "boooobs", "booooobs", "booooooobs", "bootleg", "booty", "booty call", "bosomy", "boutique", "bowel", "bra",
"bracket", "brackets", "bradley", "brakes", "bras", "brazil", "brazzers", "breach", "breast", "breast cancer", "breasts",
"breeder", "breeding", "breeds", "brett kavanaugh", "briefs", "brighten", "britney", "brittany", "broad", "broadband", "brooke",
"browser", "browsing", "brunette", "brutal", "buceta", "buck", "bucks", "bufing", "bukkake", "bulge", "bulges", "bulimia",
"bull", "bullshit", "bullshits", "bullshitted", "bully", "bullying", "buncombe", "bundle", "buried", "burke", "burning",
"burst", "buses", "businesses", "bust a load", "busty", "busy", "butt", "butt plug", "buttcheeks", "buttfuck", "buttfucker",
"butthole", "butthurt", "buttmuch", "buttplug", "butts", "buttsex", "bytes", "c-o-c-k", "c-u-n-t", "c.0.c.k", "c.o.c.k.",
"c.u.n.t", "c0ck", "cabinets", "caca", "calculations", "cam girl", "camel toe", "cameltoe", "cameras", "camps", "cancer",
"cannabidiol", "cannabis", "cannabutter", "cannon", "caps", "captured", "cardiovascular", "carolina", "carona", "caronavirus",
"carpetmuncher", "carriers", "cartoons", "cases", "cashiers", "casinos", "casio", "cassandra", "cassie", "caught", "causing", "cdna",
"cds", "cellular", "cemetery", "censor", "censored", "centers", "cet", "challenge", "chances", "charger", "charlie hebdo",
"cheat", "cheated", "cheating", "cheats", "checks", "cheeks", "cheerfully", "cheerleader", "cheers", "chemtrails", "chester
bennington", "chesticle", "chevy", "chewey", "chi", "chick", "child", "china", "chingada madre", "chink", "cho", "chode", "choice",
"choices", "choose", "chris cornell", "christ", "christians", "christina grimmie", "christine", "christine gambito", "chuck",
"chuj", "church", "churches", "cialis", "cigarette", "cigarettes", "cindy", "cinnamon", "cio", "circle jerk", "circulation",
"circumcise", "circumcised", "circumcision", "civil war", "cl", "claire", "clara chung", "cleaners", "cleavage", "clit", "clit
licker", "clitoris", "clitorus", "clits", "clitty", "closes", "clown", "clusterfuck", "clutching", "cn", "cnn", "coalition",
"cocain", "cocaine", "cock", "cockfucker", "cockhead", "cockmonkey", "cockmunch", "cockmuncher", "cocks", "cocksucked",
"cocksucker", "cocksuckers", "cocksucking", "coffin", "coffin dodger", "coins", "coital", "coitus", "coldly", "collecting",
"collin", "colon", "colorado", "columbine", "com", "comfortable", "commie", "commit", "committed", "common", "communications",
"communism", "communist", "communists", "complain", "complaint", "compliant", "concentrate", "concentration camp", "concerts",
"conditions", "condom", "condoms", "confine", "confirm", "conflict", "conflicts", "connector", "connectors", "consecutive",
"consent", "consequences", "considerably", "consistently", "constraint", "constructed", "contain", "container", "contains",
"contaminate", "contaminated", "contamination", "content", "contracts", "contrast", "contribution", "contributions", "controversial",
"controversy", "convicted", "cookbook", "coom", "coomer", "coon", "coons", "copy", "cornhole", "corona", "corona virus",
"coronavirus", "corps", "corpse", "corpus", "cougar", "cough", "coughing", "counted", "country", "countryside", "counts", "coupons",
"courier", "courtesy", "cousin", "cousins", "cove", "covid", "covid 19", "covid19", "cox", "cp", "crack", "crackhead",
"crackwhore", "crap", "crawford", "crazy", "creampie", "creating", "creations", "cremation", "cretin", "crime", "crimes", "crips",
"croatia", "crops", "crossdress", "crossdresser", "crossdressing", "crucial", "cruel", "cruelty", "cs:go", "cu", "cuba", "cuck",
"cuckold", "cucumber", "cultures", "cum", "cumdumpster", "cumguzzler", "cumming", "cums", "cumshot", "cumshots", "cumslut",
"cunilingus", "cunillingus", "cunnilingus", "cunny", "cunt", "cuntass", "cunthole", "cuntlick", "cuntlicking", "cunts", "cuntslut",
"cure", "custody", "customer", "customers", "customs", "cut", "cutting", "cw", "cyberfucker", "cyberfucking", "cyprus",
"cyst", "czech", "czn burak", "d0uche", "d1ck", "damages", "dammit", "damn", "damned", "damnit", "dangerous", "dank", "dank
memes", "dap", "dare", "database", "daterape", "daughters", "davis", "dayton", "dead", "dead body", "deadbeat", "deadly",
"dealer", "dealers", "dealing", "death", "death metal", "deaths", "debug", "dec", "decade", "decades", "decay", "deceased",
"decide", "decided", "dee", "deep throat", "deeply", "deepthroat", "deez", "deez nuts", "definitions", "degree", "degrees",
"delaware", "delay", "delhi", "deliver", "delivering", "delivery", "dell", "delta", "democrat", "democratic", "democrats",
"demonetized", "denied", "dental abscess", "deny", "dependent", "depress", "depressing", "depression", "derby", "describes",
"description", "desire", "desired", "desmond amofah", "destination", "destroyed", "destruction", "detailed", "detected", "detection",
"determination", "determine", "deutsche", "deviant", "devices", "devil", "devils", "dh", "diarrhea", "dick", "dick cheney", "dicke",
"dickface", "dickhead", "dickheads", "dicks", "dicksucker", "dicksucking", "dickwad", "dickweed", "diddle", "diddler", "diddling",
"die", "died", "dies", "digit", "digits", "dildo", "dildos", "dining", "dipshit", "direct", "directioners", "dirsa", "dirty",
"dirty sanchez", "disabled", "disapproving", "disciplinary", "disclaimer", "discount", "discusses", "discussing", "diseases",
"disgusted", "disgusting", "dishonest", "disorders", "dispatch", "display", "disposition", "disturb", "disturbed", "disturbing",
"div", "divx", "dlck", "documents", "doe", "dog style", "doggie style", "doggiestyle", "doggin", "dogging", "doggy style",
"doggystyle", "dollars", "dom", "domination", "dominatrix", "dominion", "dommes", "donate", "donated", "dong", "donkey punch",
"donor", "douche", "douchebag", "douchebags", "douchecanoe", "douchewaffle", "douchey", "down", "download", "downloads",
"doxxing", "dozens", "dp", "dpi", "dr.dre", "drag", "drainage", "dress", "dresses", "drove", "drug", "drugs", "drunk", "dry",
"dry hump", "dublin", "duche", "dude", "dumb", "dumbass", "dumbfuck", "dumbshit", "dump", "duncan", "durham", "dyke", "e",
"earwax", "eat", "eat out", "eating", "eating out", "ebony", "ebook", "ebooks", "ecchi", "economies", "ecstasy", "ecuador",
"eden", "edgy", "education", "educators", "ee", "egirl", "egirls", "eighth", "either", "ejaculate", "ejaculated",
"ejaculates", "ejaculating", "ejaculatings", "ejaculation", "ejakulate", "el chapo", "election", "election fraud", "elections",
"electoral", "electrical", "electronics", "element", "elephant", "elevation", "elevator", "elevators", "eliminate", "elliot
rodger", "eloise", "elsa", "elsagate", "em", "emerge", "emergency", "emily graslie", "employees", "employers", "enclosure",
"encoding", "encourage", "encouraged", "enhanced", "enhancing", "enjoy", "enjoyed", "enlarge", "enlarged", "enter",
"entertainment", "entitled", "environmental", "environments", "epson", "epstein", "epstein didn't kill himself", "equivalent", "erect",
"erectile dysfunction", "erecting", "erection", "erotic", "erotica", "errors", "escherichia coli", "escort", "escorts",
"estimate", "estimates", "eternal", "ethic", "ethical", "ethiopia", "etika", "eugenia cooney", "euro", "eurotrash", "eva",
"evans", "evidence", "ewok", "ewoks", "ex boyfriend", "examines", "example", "examples", "exams", "excellent", "excess",
"excessive", "excited", "excitement", "execute", "executed", "execution", "existed", "existing", "expanding", "expedia", "expense",
"experiences", "explicit", "exploit", "exploitation", "exploited", "explosion", "explosive", "explosive diarrhea", "explosives",
"express", "expressed", "extraction", "extreme", "extremely", "ez", "f", "f u c k", "f u c k e r", "f-u-c-k", "f.o.r.d.",
"f.u.c.k", "face", "faces", "facial", "fack", "fag", "fagfucker", "fagged", "faggit", "faggot", "faggots", "faggs", "faghag",
"fagot", "fagots", "fags", "fails", "faint", "fainted", "faithful", "falls", "fanny", "fap", "fapping", "faps", "farming",
"farms", "farther", "farting", "fartknocker", "farts", "fat", "fatal", "fatass", "fathers", "fatty", "faucet", "favors", "fbi",
"fcuk", "fcuking", "fecal", "feed", "feeding", "feeling", "feet", "fellate", "fellatio", "feltcher", "female", "females",
"femdom", "feminazi", "feminism", "feminist", "feminists", "feminized", "festival", "festivals", "fetish", "fetishes",
"fiction", "fifth", "finances", "finder", "fingerbang", "fingered", "fingerfuck", "fingerfucked", "fingerfucks", "fingering",
"finish", "finishing", "fired", "fisted", "fistfuck", "fistfucked", "fistfucker", "fistfuckers", "fistfucking", "fisting",
"fleet", "fleets", "flesh", "fleshlight", "flexible", "floppy", "floral", "flowers", "foad", "foam", "focal", "focused",
"followed", "fondle", "fondled", "fooker", "footjob", "force feminized", "forced", "foreskin", "foreskins", "forestry", "format",
"formats", "forward", "fountain", "fountains", "francesca", "fraser", "freak accident", "freaky", "free", "freeware",
"frequently", "freshman", "freshmen", "frick", "fright", "frighten", "frightening", "from", "fry", "fs", "ftw", "fu", "fubu", "fuc",
"fuck", "fucka", "fuckass", "fuckbag", "fuckboi", "fuckboy", "fucked", "fuckedup", "fucker", "fuckers", "fuckface",
"fuckgirl", "fuckheads", "fuckhole", "fuckin", "fucking", "fuckings", "fuckme", "fuckoff", "fucks", "fucktard", "fucktards",
"fucktoy", "fuckup", "fuckwhit", "fuckwit", "fuk", "fuker", "fukker", "fukkin", "fuks", "full", "full movie", "funeral",
"funerals", "futanari", "fvck", "g-spot", "gabriel", "gabrielle", "gai", "gallbladder cancer", "galleries", "gallon", "gallons",
"gambling", "gang bang", "gang member", "gangbang", "gangbanged", "gangbangs", "gash", "gave", "gay", "gay lord", "gay marriage",
"gay pride", "gayass", "gayfuck", "gays", "gaysex", "gd", "gdi", "gender", "genital", "genital herpes", "genital warts",
"genitals", "genocide", "gentlemen", "genuinely", "geometry", "george", "gestapo", "gey", "ghetto", "ghey", "ghz", "giantess",
"gibs", "gilf", "ginger", "gino", "giovanni", "girl on top", "girls gone wild", "give", "gl", "glans", "glen", "glenn", "gmt",
"gnome", "goatse", "gobshite", "god-damned", "godamn", "godamnit", "goddam", "goddamn", "goddamned", "gods", "goes", "going",
"goo", "goo girl", "good charlotte", "goodbye", "gook", "gooks", "gore", "goregasm", "gory", "gotten", "government",
"governmental", "governments", "gp", "gr", "grab", "graduate", "grain", "grande", "graphic", "gras", "gratis", "gratuit", "gravy",
"greenhouse", "grey", "grill", "grind", "grinding", "grope", "groped", "groping", "group", "groupie", "grow", "gsm", "gspot",
"gtfo", "gullible", "guro", "gypsy", "h0m0", "hack", "hacked", "hacker", "hacks", "hailey", "hairy", "hand job", "hand over",
"handed", "handjob", "handjobs", "hang", "happy tree friends", "harass", "harassed", "harassment", "harbor", "hard", "hard on",
"hardcore dancing", "hardcoresex", "harder", "hardware", "hash", "hater", "have", "haven", "having", "haylee", "hdtv", "he-she",
"head", "headquarters", "heads", "healing", "health", "healthy", "heavily", "heights", "hell", "hemp", "hentai", "heritage",
"heroin", "herpes", "hetero", "hetrosexual", "hh", "hiatus hernia", "high", "highland", "hitler", "hiv", "hmu", "hoax", "hobo",
"hoer", "holder", "holocaust", "holohoax", "holy", "homewrecker", "homo", "homoerotic", "homoey", "homophobe", "homophobic",
"homosexual", "honkey", "honors", "honour", "hook", "hooker", "hookers", "hookup", "hootch", "hooters", "hopeful", "hopefully",
"horndog", "horney", "horniest", "horny", "horrible", "horror", "hose", "host", "hosts", "hot", "hot carl", "hot chick", "hot
mess", "hotbox", "hotels", "hotsex", "hottest", "howtobasic", "huge", "human", "humanities", "humor", "hump", "humped",
"humping", "hundredth", "hung", "hunter biden", "husband", "hybrid", "hydroxychloroquine", "hymen", "hyper responder", "hyphy",
"hypocrite", "hz", "ice", "ice cream", "icp", "idaho", "idiot", "illegal", "illinois", "illustrate", "ily", "im rick james bitch",
"images", "imagine", "img", "immoral", "imp", "implementation", "implication", "import", "importance", "impose",
"inappropriate", "inbred", "inbreed", "incel", "incest", "inches", "incidents", "incl", "included", "income", "incomplete",
"incorporate", "incorrect", "increasingly", "independance", "independant", "indices", "indonesia", "induction", "industry",
"inflation", "infowars", "initiated", "injection", "injun", "inns", "inserted", "inside", "insights", "inspection", "institute",
"institution", "instruments", "intense", "intent", "intercourse", "interesting", "interfaces", "interim", "internet", "internship",
"interracial", "intervals", "intifada", "intimate", "intl", "introvert", "introverted", "investigations", "investors", "invisible",
"invitation", "involve", "iran", "iraq", "iraqi", "irene", "irie", "irish republican army", "irrigation", "isabella", "isil",
"isis", "islam", "iso", "israel", "israeli", "issued", "issues", "istanbul", "italia", "italy", "itchy", "item", "iyad
el-baghdadi", "izzy", "j.a.p.", "jackass", "jacked", "jackie", "jacking off", "jackoff", "jackson", "jacksonville", "jada",
"jaguar", "jail bait", "jailbait", "jamie", "janet", "jap", "japs", "jar", "jared", "jared knabenbauer", "jared taylor",
"jeffree epstein", "jeffree epstein didn't kill himself", "jehovahs witnesses", "jenna", "jenny", "jeremiah", "jerk",
"jerk-off", "jerkoff", "jessi slaughter", "jessica", "jews", "jigaboo", "jiggaboo", "jigger", "jihad", "jin", "jiz", "jizz",
"jizzed", "jocelyn", "jock", "joe biden", "john wayne gacy", "joint", "joints", "joker", "jon jafari", "jose", "josh",
"journalists", "judge", "judgment", "juggs", "juice", "juicy", "kafir", "kalergi", "kay", "kaylee", "keira", "kelsey", "kerry",
"kevin spacey", "kg", "kid", "kidnap", "kidnapping", "kikes", "kill", "killed", "killer", "killing", "kinbaku", "kinky",
"kissing", "kk", "kkk", "klan", "knacker", "knife", "knowing", "knowledgestorm", "known", "kodak", "kondum", "kooches",
"kristen", "ku klux klan", "kurwa", "kush", "kw", "kyler", "labia", "lacey", "lacking", "lad", "laden", "laila", "lame", "las
vegas shooting", "latex", "latinas", "latinx", "laundry", "lawrence", "laws", "lb", "lbs", "lease", "leased", "least",
"legit", "legs", "leisure", "len", "lender", "lesbian", "lesbians", "lesbo", "lesbos", "less", "lessons", "lets", "lexie",
"lezza", "lezzie", "lg", "lgbt", "lgbtqia", "libraries", "libs", "licenses", "lick", "licking", "liechtenstein", "liliana",
"lily", "lina", "lindsay", "lindsay shepherd", "lined", "lingerie", "link", "linked", "lips", "lists", "lithuania",
"liveleak", "livesex", "llc", "lm", "lmao", "lo", "logitech", "lolicon", "lolita", "loner", "loose", "los", "loser", "louie ck",
"louis ck", "lounge", "lovemaking", "lover", "lqtm", "ls", "lsd", "lube", "lucia", "lug", "lung cancer", "lust", "lustful",
"made", "magical", "mail", "mails", "mailto", "maintained", "male", "males", "managing", "manchester", "manner", "manually",
"maoist", "marcos", "marijuana", "marketing", "marry", "martha", "maryland", "massa", "massacre", "massage", "massive",
"master-bate", "masterbat", "masterbate", "masterbating", "masterbation", "masturbate", "masturbating", "masturbation",
"masturbators", "matched", "mating", "mats", "mature", "mb", "me too", "meathead", "media", "medicaid", "medical", "medicare",
"medications", "meetup", "mega", "members", "memorial", "mens", "menses", "menstrual", "ment", "mental", "mental health", "mentally",
"mentor", "menu", "menus", "merde", "mere", "merely", "mesothelioma", "meth", "meth amphetamine", "methamphetamine", "methods",
"metoo", "mexican", "mexicans", "mf", "mgtow", "mi", "michel", "microwave", "middle finger", "midget", "midlands", "milan",
"milf", "milfhunter", "milfs", "milk", "mindfuck", "minecraft", "minimal", "ministries", "minneapolis", "minnesota",
"minorities", "minority", "miscarriage", "misconduct", "missionary", "missionary position", "mississippi", "missouri", "mistakes",
"mistress", "ml", "mm", "mo-fo", "mocha uson", "model", "modelling", "moderate", "modification", "module", "molest", "molester",
"mom", "momo", "mono", "morally", "moss", "most", "motels", "mothafucka", "mothafuckas", "mothafuckaz", "mothafucker",
"mothafuckers", "mothafuckin", "mothafucking", "mother", "motherfuck", "motherfucka", "motherfucker", "motherfuckers", "motherfuckin",
"motherfucking", "motherfuckings", "mouth cancer", "movies", "mrna", "msnbc", "muff diver", "muff puff", "multimedia", "multiple",
"murder", "murdered", "murderer", "museums", "muslim", "muslims", "mutha", "muther", "mutherfucker", "mw", "my", "mya", "myers",
"n word", "n00b", "n1gga", "n1gger", "nadia", "naggers", "naked", "nambla", "namely", "napalm", "naperville", "narrow",
"nasty", "natalia", "nationally", "naughty", "naveah", "nazi", "nazism", "nearest", "neatly", "necro", "necrophilia", "neds",
"needed", "needle", "negotiate", "negotiation", "negotiations", "negro", "neko", "neo-nazi", "neonazi", "nested", "nevaeh",
"nevertheless", "new canaan", "new zealand", "newb", "newer", "nh", "nicholas", "nickelodeon", "nig nog", "nigg3r", "nigga", "niggah",
"niggas", "niggaz", "nigger", "niggerfaggot", "niggers", "nigglet", "nightlife", "niglet", "nigs", "nike", "nikita", "nikki",
"ninja", "nip", "nipple", "nipples", "noble", "nofap", "nonconforming", "nonconformist", "norfolk", "normie", "north", "north
carolina", "north dakota", "north korea", "northwest", "nose", "notebook", "noted", "notices", "notion", "novel", "novels",
"nsfw", "ntsc", "nuclear explosion", "nude", "nudes", "nudist", "nudity", "nug", "nuke", "nurse", "nursing", "nut", "nut
sack", "nuts", "nutsack", "nutten", "nv", "nympho", "oaks", "obama", "obituaries", "obnoxious", "oboe", "oc", "occasionally",
"occupations", "ocd", "odd", "odds", "oecd", "oem", "offend", "offensive", "offered", "ogre", "ogres", "oh noes", "oj", "oklahoma",
"old", "olympus", "omg", "oml", "one night stand", "oof", "oompa loompa", "openly", "opeth", "oppai", "oppose", "oral", "oral
sex", "orchestra", "ordinance", "organisations", "organised", "organizer", "orgasim", "orgasims", "orgasm", "orgasmic",
"orgasms", "orgies", "orgy", "oriental", "osama", "osama bin laden", "outdoor", "outlet", "outline", "ovarian cancer", "ovarian
cyst", "ovary", "oven", "owen", "own", "ownage", "oxymoron", "p.u.s.s.y.", "p0rn", "packages", "packs", "paedo",
"paedophile", "paid", "painful", "painted", "paki", "pal", "pale", "palestine", "palestinian", "panic", "panic disorder", "pansy",
"pantie", "panties", "pants", "panty", "pantyhose", "papua", "par", "parameters", "park", "participants", "participated",
"partners", "parts", "password", "paste", "patient", "patients", "patrick", "patriot", "payday", "paypal", "payroll", "pci",
"pcp", "pda", "pdf", "pdt", "pea", "peaceful", "pecker", "pedo", "pedobear", "pedophile", "pedophilia", "pedophiliac", "pee",
"pee pee", "peeing", "pegging", "pencil", "pencils", "pendant", "penetration", "penial", "penile", "penis", "pension",
"perfection", "periods", "permalink", "persons", "pervert", "perverted", "perverts", "pete wentz", "phallus", "phi", "phonesex",
"photos", "phuck", "phuking", "phukked", "phukking", "pic", "picture", "pills", "ping", "pingas", "piss", "piss off", "piss
pig", "pissed", "pissed off", "pisser", "pisses", "pissflaps", "pissin", "pissing", "pisspig", "pittsburgh", "pizzagate",
"plasma", "playboy", "pleasant", "pleasing", "pleasure", "plug", "pod", "pods", "poems", "pogo the clown", "pointed", "polack",
"police brutality", "polite", "politician", "poo", "poof", "poonany", "poop", "poopchute", "poops", "poopuncher", "porch
monkey", "porchmonkey", "porn", "pornhub", "porno", "pornography", "pornos", "portugal", "pos", "position", "positions",
"postcard", "posted", "pot", "pot head", "potentially", "potty", "pounds", "pour", "poured", "powder", "prefer", "premium",
"prep", "prescription", "presentation", "pretend", "previous", "prig", "priorities", "prius", "privacy", "private",
"pro-choice", "probable", "procedures", "proceedings", "procrastination", "productions", "profiles", "profit", "profvide",
"program", "programme", "programs", "projared", "projector", "promo", "pron", "prophet", "prospects", "prostate cancer",
"prostitute", "prostitutes", "prostitution", "protecting", "proven", "provide", "provided", "providing", "prude", "pubes", "pubic",
"pubic hair", "publisher", "puke", "puked", "pukes", "pumps", "punanny", "punany", "punishment", "punishments", "purchasing",
"pursuant", "puss", "pussi", "pussie", "pussies", "pussy", "pussylicking", "pussys", "puto", "puzzles", "qanon", "qtf", "qua",
"quackityhq", "quad-sexual", "quake", "quang", "quarf", "quarterback", "quarterpounder", "quasi", "que", "queef", "queenie",
"queer", "queet", "queff", "quentin", "questionnaire", "quiche", "quickie", "quief", "quinning", "quinton", "quizno", "qweef",
"qwert", "r kelly", "r18", "race", "race war", "rachel", "racism", "racist", "raised", "raising", "rally", "ran", "rape",
"raped", "rapey", "raping", "rapist", "rated", "raymond", "reading", "realtor", "recent", "records", "recovery", "recreation",
"rectal", "reddit", "redhead", "redneck", "reds", "reed", "referral", "referrals", "refugee", "refugees", "refund", "regions",
"regularly", "regulated", "regulation", "rehab", "rehabilitation", "reich", "relate", "relating", "relation", "relaxing",
"reliable", "remarks", "remedies", "removal", "removed", "rendering", "rep", "repeatedly", "reported", "reporter",
"representation", "representative", "reproduction", "request", "requests", "reseller", "respondent", "restaurant", "restaurants",
"restrict", "restriction", "retard", "retarded", "retards", "rev", "revenues", "reverse cowgirl", "revolutionary", "rfc", "rica",
"ricardo milos", "richard spencer", "richardson", "rick", "rico", "rigs", "rimjob", "rimming", "rioters", "riots", "rip",
"risk", "risks", "risky", "rivers", "riverside", "roasting", "robbery", "robertson", "roblox", "rohypnol", "roman", "romance",
"romantic", "roms", "roofies", "rory", "router", "rr", "ru", "ruchanie", "rucka rucka ali", "rude", "rufies", "ruin", "ruined",
"rule 34", "ruled", "rumour", "russian", "rwanda", "rylee", "ryona", "s-h-i-t", "s.h.i.t.", "s&m", "s3x", "sabrina", "sack",
"sacrifice", "saddam", "sadism", "sadist", "sadly", "sake", "salvia", "sam pepper", "sandy", "sandy hook", "sara", "satan",
"satisfying", "sausage-fest", "saving", "savings", "say", "says", "sc", "scale", "scally", "scam", "scandal", "scanner",
"schedules", "scheduling", "schlong", "scientist", "scissoring", "scottish", "screenshots", "screw", "screwed", "scrog", "scrot",
"scrotum", "scrud", "scum", "seattle", "secretariat", "secretary", "secretly", "seduce", "seduced", "seks", "selling", "sells",
"semen", "sending", "sends", "sensor", "sep", "series", "seriously", "servant", "serves", "service", "sex", "sex work", "sex
worker", "sexcam", "sexism", "sexist", "sexo", "sext", "sexting", "sextortion", "sexual", "sexual health", "sexuality",
"sexually", "sexually transmitted infections", "sexy", "sexy time", "sh!t", "shagging", "shakespeare", "shame", "shamedame",
"shane", "shane dawson", "shanghai", "share", "shat", "shave", "sheep", "sheet", "sheets", "sheffield", "shemale", "shemales",
"sheriff", "shibari", "shit", "shitbag", "shitbrains", "shite", "shited", "shitface", "shitfaced", "shitfuck", "shithead",
"shithole", "shithouse", "shitpost", "shitposting", "shits", "shitted", "shitter", "shitting", "shitty", "shock", "shocking",
"shooting", "shoplifter", "shot", "shota", "shotacon", "shrek", "shrimping", "shroom", "shrooms", "shut", "shy", "si", "side",
"silicon", "simon", "simple plan", "simplified", "simply", "sip", "sites", "situation", "situations", "skag", "skiing", "skin
cancer", "skins", "skirt", "sku", "skullfuck", "slaps", "slaughtering", "slave", "slavery", "slaves", "slayer", "sleaze",
"sleazy", "sleeping", "sleeps", "slowly", "slut", "sluts", "small", "smeg", "smegma", "smell", "smexy", "smoking", "smut",
"smutty", "snatch", "snowballing", "snowflake", "snuff", "soa", "society", "sock", "sodomize", "sodomy", "softly",
"sonofabitch", "sore", "south carolina", "spaces", "spank", "spanking", "spas", "sperm", "spicy", "spine", "spirits", "spiritual",
"spokesman", "sponsors", "spook", "springer", "springs", "spy", "spy cam", "spycam", "sql", "squirt", "squirting", "stair",
"stamps", "stan", "standard", "starsmerchant", "starts", "stays", "std", "steal", "stem", "stephanie", "sterling", "steroids",
"stfu", "stiffly", "sting", "stir", "stockings", "stoned", "stoner", "strap on", "strapon", "strictly", "strip", "strip club",
"striped", "stripper", "strippers", "stripping", "strips", "strongly", "stuck", "stuffed", "su", "subjective", "subjects",
"submitted", "subscriptions", "subtle", "succubus", "suck", "sucked", "sucking", "sucks", "sudden", "suffered", "suggesting",
"suggests", "suicide", "suitable", "suites", "sunglasses", "sunny", "superb", "supervision", "supplemental", "supply",
"supremacist", "surfing", "surname", "surrouding", "surveillance video", "suspect", "sv", "swastika", "swearing", "swim", "swingers",
"sympathy", "synthetic", "syria", "system of a down", "t bag", "t.j", "tablets", "tahoe", "taint", "taking the piss", "talia",
"tall", "tana mongeau", "tank", "tanks", "tanzania", "targeted", "tattoo", "tattoos", "teabagging", "technician", "ted bundy",
"ted fu", "teen", "teens", "teeth", "telecharger", "temple", "tend", "term", "termination", "terminology", "terrace",
"terrible", "terrorism", "terrorist", "terrorists", "tessa", "tested", "testicle", "testicles", "testicular cancer", "texas",
"text", "tgp", "that", "thc", "the bible", "the big lie", "the man", "the strokes", "then", "there", "thereby", "these",
"thick", "third", "thomson", "thong", "those", "threat", "threesome", "thriller", "throating", "throughout", "thrown", "thug",
"thumbnails", "thy", "thyroid cancer", "tickets", "tide", "tight", "tilf", "timber", "times", "timothy mcveigh", "tissue", "tit",
"titfuck", "titi", "tities", "titled", "tits", "titt", "titten", "tittie", "titties", "titty", "to", "tobago", "toby", "toby
turner", "todd", "toe", "toilet", "tolerance", "tommy sotomayor", "tongue", "tons", "took", "toolbox", "topless", "tops",
"torrent", "torture", "toshiba", "touched", "tourism", "tourist", "towel", "townie", "township", "toys", "tr", "trade up",
"traditionally", "trainer", "trance", "tranny", "trans", "transition", "translations", "transmit", "trash", "trauma", "travelers",
"travels", "treasury", "treatment", "treaty", "trent", "treo", "tri-sexual", "trial", "tribadism", "tribute", "trigger",
"triggered", "trim", "triple", "trisha paytas", "trolling", "troop", "troops", "trump administration", "trustee", "ts", "tsunami",
"tubes", "tue", "tumor", "tunes", "tuning", "turk", "twat", "twats", "twerk", "twerking", "twink", "twinks", "twisted",
"twunt", "uh-oh spaghetti-o's", "ui", "ukraine", "ultimately", "umemployment", "unacceptable", "unc.", "uncensored",
"undefined", "undertaken", "underwear", "undress", "undressing", "unfuckable", "uniboob", "unions", "unionville", "unionville
girls", "unkind", "unpleasant", "unsuccessful", "unwillingly", "uploaded", "upon", "upperdecker", "upskirt", "upskirts",
"urge", "url", "usage", "usd", "user", "username", "usmc", "uw", "uyghur muslim", "uyghur muslims", "vacancies", "vacations",
"vacuum", "vaffanculo", "vag", "vaganus", "vagina", "vaginal", "vaginal thrush", "vagitarian", "vajayjay", "valerie",
"validation", "valley", "valued", "vape", "varieties", "various", "vart", "varun", "vatican", "vbucks", "vc", "vegetable", "veggie",
"velocity", "vendors", "ventures", "verification", "versions", "verzeichnis", "veterinary", "viagra", "vibrator", "vibrators",
"vicky", "victim", "victims", "vid", "vids", "vidya iyer", "vienna", "viet cong", "vietnamese", "vii", "viola", "violence",
"violent", "violently", "vip", "virgin", "virginia beach", "virginia tech shooting", "virginity", "virtually", "virus",
"visible", "visitor", "vivian", "vodka", "voluptuous", "vomit", "vore", "voter", "voter fraud", "voters", "voyeur", "voyeurweb",
"vsnet", "vujade", "vulgar", "vulva", "vulval cancer", "vuvuzela", "wab", "wag", "waiver", "wake", "wal-rus", "wallflower",
"walt", "wank", "wanna", "war", "war crimes", "warming", "warnings", "watch free", "watch online", "watched", "web",
"webmaster", "webshots", "webster", "wed", "wedgie", "weed", "weeds", "welsh", "wet", "wheels", "whigger", "white", "white boy",
"white girl", "white people", "white power", "white pride", "white privilege", "white supremacists", "white trash", "whitey",
"whore", "whorehouse", "whores", "wisconsin", "wit", "witnessed", "witnesses", "wives", "wog", "women", "womens", "womp",
"wordpress", "worker", "worldcat", "wounded", "wow", "wright", "wtf", "wuhan", "ww", "x pill", "x-bomb", "x-japan", "x-rated",
"xax", "xaxa", "xboned", "xbox nigga", "xenia", "xenogears", "xerox", "xerxes", "xhtml", "xia", "xigdem", "ximena", "xing",
"xml", "xnxx", "xqc", "xterra", "xtina", "xtreme", "xtube", "xvideos", "xx", "xxx", "xxx-tentacion", "xxxx", "xzibit",
"y'all", "y2k", "yah", "yandere", "yanni", "yaoi", "yar", "yard ape", "yasmin", "yay area", "yayo", "yea", "years", "yesn't",
"yoga pants", "yonk", "yoot", "you", "youtube algorithm", "youtube poop", "yr", "ytf", "yu", "yuh", "yukon", "yum-yum",
"yummy", "yvonne", "zainab", "zambia", "zayn malik", "zealand", "zit", "zombie apocalypse", "zoophilia", "zorb", "zoya",
"zulu", "zumiez"] 
